meta_product_name: "JoinCodeBuddies"
meta_title: "JoinCodeBuddies - Join our community, Code, build and learn"
meta_description: "Many of us have amazing ideas and we are looking for the perfect team to build it."
meta_image: "joincodebuddies_meta.jpg" # should exist in `app/assets/images/`
